#cloud-config

%{ if public_instance == "false" }
#disable_root: false
disable_root: false
ssh_pwauth: true
chpasswd:
  expire: false
  list: |
    root:linux
%{ endif }

%{ if image == "opensuse152"}

zypper:
    repos:
      - id: opensuse_pool_repo
        name: opensuse_pool_repo
        baseurl: http://download.opensuse.org/distribution/leap/15.2/repo/oss/
        enabled: 1
        autorefresh: 1

packages: ["salt-minion"]

%{ endif }

%{ if image == "sles15sp2"}

#zypper:
 # repos:
    #- id: os_pool_repo
    #  name: os_pool_repo
    #  baseurl: http://${mirror_url}/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product
    #  enabled: 1
    #  autorefresh: 1

packages: ["salt-minion"]
%{ endif }

